apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata: 
  name: php-apache

spec: 
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment 
    name: php-apache
  targetCPUUtilizationPercentage: 50

status: 
  currentCPUUtilizationPercentage: 0
  currentReplicas: 2
  desiredReplicas: 2
